/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package t2207e_java2_ngay9;

/**
 *
 * @author tranthimaihien
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelMain = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mniQuanlylophoc = new javax.swing.JMenuItem();
        mniQuanlusinhvien = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        PanelMain.setLayout(new java.awt.CardLayout());
        jPanel1.add(PanelMain, "card2");

        jMenuBar1.setSize(new java.awt.Dimension(755, 245));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Quản lý");

        mniQuanlylophoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniQuanlylophoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t2207e_java2_ngay9/Icon/ion2.gif"))); // NOI18N
        mniQuanlylophoc.setText("Quản lý lớp học");
        mniQuanlylophoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanlylophocActionPerformed(evt);
            }
        });
        jMenu3.add(mniQuanlylophoc);

        mniQuanlusinhvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniQuanlusinhvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t2207e_java2_ngay9/Icon/ion1.gif"))); // NOI18N
        mniQuanlusinhvien.setText("Quản lý sinh viên");
        mniQuanlusinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanlusinhvienActionPerformed(evt);
            }
        });
        jMenu3.add(mniQuanlusinhvien);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniQuanlylophocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQuanlylophocActionPerformed
        // TODO add your handling code here:
        PanelQuanlylophoc qllop=new PanelQuanlylophoc();
        PanelMain.removeAll(); // xoá các Panel con nếu có
        PanelMain.add(qllop);
        PanelMain.repaint();
        PanelMain.validate();
    }//GEN-LAST:event_mniQuanlylophocActionPerformed

    private void mniQuanlusinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQuanlusinhvienActionPerformed
        // TODO add your handling code here:
        PanelQuanlysinhvien qlsv=new PanelQuanlysinhvien();
        PanelMain.removeAll(); // xoá các Panel con nếu có
        PanelMain.add(qlsv);
        PanelMain.repaint();
        PanelMain.validate();
    }//GEN-LAST:event_mniQuanlusinhvienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMain;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mniQuanlusinhvien;
    private javax.swing.JMenuItem mniQuanlylophoc;
    // End of variables declaration//GEN-END:variables
}
