/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyNotePad2;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Admin
 */
public class MyNotePad2Form extends javax.swing.JFrame {

    /**
     * Creates new form MyNotePad2Form
     */
    public MyNotePad2Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        edt_noidung = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nmi_new = new javax.swing.JMenuItem();
        mni_open = new javax.swing.JMenuItem();
        mni_save_as = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        edt_noidung.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(edt_noidung);

        jMenu1.setText("Hệ thống");

        nmi_new.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        nmi_new.setText("Tạo mới");
        nmi_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmi_newActionPerformed(evt);
            }
        });
        jMenu1.add(nmi_new);

        mni_open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mni_open.setText("Mở file");
        mni_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_openActionPerformed(evt);
            }
        });
        jMenu1.add(mni_open);

        mni_save_as.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mni_save_as.setText("Ghi ra tệp mới");
        mni_save_as.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_save_asActionPerformed(evt);
            }
        });
        jMenu1.add(mni_save_as);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nmi_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmi_newActionPerformed
        // TODO add your handling code here:
        edt_noidung.setText("");
    }//GEN-LAST:event_nmi_newActionPerformed

    private void mni_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_openActionPerformed
        // TODO add your handling code here:
        
        //mở file từ hệ thống
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        File file = fc.getSelectedFile();
        //đọc nội dung và hiển thị lên editor
        FileReader fr;
        try {
            fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            String str;
            String noidung ="";
            while( (str = br.readLine()) !=null)//vòng lặp đọc từng dòng của tệp và lưu vào biến str
            {
                if(noidung.equals(""))//dòng đầu
                    noidung += str;
                else//từ dòng 2 phải cộng thêm dấu xuống dòng
                    noidung +=  "\n" + str;
            }
            edt_noidung.setText(noidung);
            br.close();
            fr.close();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MyNotePad2Form.class.getName()).log(Level.SEVERE, null, ex);
        }catch (IOException ex) {
                Logger.getLogger(MyNotePad2Form.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_mni_openActionPerformed

    private void mni_save_asActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_save_asActionPerformed
         // TODO add your handling code here:
        //mở file từ hệ thống
        JFileChooser fc = new JFileChooser();
        fc.showSaveDialog(this);
        File file = fc.getSelectedFile();
            
   
            //ghi file
        FileOutputStream fo;
        try {
            fo = new FileOutputStream(file,false);
            PrintWriter pw = new PrintWriter(fo);
            String noidung = edt_noidung.getText();
            pw.println(noidung);
            pw.close();
            try {
                fo.close();
            } catch (IOException ex) {
                Logger.getLogger(MyNotePad2Form.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MyNotePad2Form.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
   
    }//GEN-LAST:event_mni_save_asActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyNotePad2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyNotePad2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyNotePad2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyNotePad2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyNotePad2Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane edt_noidung;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mni_open;
    private javax.swing.JMenuItem mni_save_as;
    private javax.swing.JMenuItem nmi_new;
    // End of variables declaration//GEN-END:variables
}
