/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import CSDL.tbLophoc;
import CSDL.tbSinhvien;
import Models.clsLophoc;
import Models.clsSinhvien;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Manh Truong
 */
public class frmQuanlySinhvien extends javax.swing.JFrame {

    /**
     * Creates new form frmQuanlySinhvien
     */
    public frmQuanlySinhvien() {
        initComponents();
        HienthiDSSinhvien();//gọi hàm hiển thị sinh viên sau khi hiển thị cửa sổ
    }
    public void HienthiDSSinhvien()
    {
        //Vector<clsSinhvien> dsSinhvien = new Vector<clsSinhvien>();
        tbSinhvien bangSinhvien = new tbSinhvien();
        int ketqua = bangSinhvien.LayDSSinhvien();
        if(ketqua<0) 
        {
            JOptionPane.showMessageDialog(this, "Lỗi CSDL");
            return;
        }
        if(bangSinhvien.list.size()>0)
        {
            DefaultTableModel dtm = (DefaultTableModel)tblDSSinhvien.getModel();
            dtm.setRowCount(0);//xóa các dòng cũ nếu có
            for(clsSinhvien sv : bangSinhvien.list)
            {
                String gioitinh = (sv.gioitinh)?"Nam":"Nữ";
             dtm.addRow(new Object[]{sv.id,sv.masv,sv.hoten,gioitinh,sv.diachi,sv.malop,sv.tenlop});
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        bnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSSinhvien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        btThem.setText("THÊM");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setText("SỬA");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        bnXoa.setText("XÓA");
        bnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnXoaActionPerformed(evt);
            }
        });

        tblDSSinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Mã sv", "Họ tên", "Giới tính", "Địa chỉ", "Mã lớp", "Lớp học"
            }
        ));
        jScrollPane1.setViewportView(tblDSSinhvien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(bnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem)
                    .addComponent(btSua)
                    .addComponent(bnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int i = tblDSSinhvien.getSelectedRow();
        if(i<0)
            JOptionPane.showMessageDialog(this, "Chưa chọn sinh viên");
        else
        {
            clsSinhvien sv = new clsSinhvien(); 
            sv.id = (int)tblDSSinhvien.getModel().getValueAt(i,0);
            sv.masv = (String)tblDSSinhvien.getModel().getValueAt(i,1);
            sv.hoten = (String)tblDSSinhvien.getModel().getValueAt(i,2);
            String gioitinh = (String)tblDSSinhvien.getModel().getValueAt(i,3);
            sv.gioitinh = (gioitinh.equals("Nam"))?true:false;
            sv.diachi = (String)tblDSSinhvien.getModel().getValueAt(i,4);
            sv.malop = (int)tblDSSinhvien.getModel().getValueAt(i,5);
            sv.tenlop = (String)tblDSSinhvien.getModel().getValueAt(i,6);
            
            frmSuaSV csSuaSV = new frmSuaSV();
            csSuaSV.sinhvien = sv;//gán sinh viên cần sửa vào form sửa
            csSuaSV.formQuanlySV = this;//gán cửa số quản lý sinh vien 
            csSuaSV.setVisible(true);
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        frmThemSV formThemSV = new frmThemSV();
        formThemSV.formQuanlySV = this;
        formThemSV.setVisible(true);
    }//GEN-LAST:event_btThemActionPerformed

    private void bnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnXoaActionPerformed
        // TODO add your handling code here:
        int i = tblDSSinhvien.getSelectedRow();
        if(i<0)
            JOptionPane.showMessageDialog(this, "Chưa chọn sinh viên");
        else
        {
            int re = JOptionPane.showConfirmDialog(this, "Chắc chắn xóa?", "Kiểm tra", JOptionPane.YES_NO_OPTION);
            if(re==JOptionPane.NO_OPTION)
                return;
            int id;
            id = (int)tblDSSinhvien.getModel().getValueAt(i,0);
            tbSinhvien bangSinhvien = new tbSinhvien();
            int kq = bangSinhvien.XoaSinhvien(id);
            if(kq>0)
            {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                HienthiDSSinhvien();
            }
            else
                JOptionPane.showMessageDialog(this, "Lỗi xóa sinh viên");
        }
    }//GEN-LAST:event_bnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnXoa;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDSSinhvien;
    // End of variables declaration//GEN-END:variables
}
