/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Demo_ComboBox2;

import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tran Manh Truong
 */
public class frmComboBox2 extends javax.swing.JFrame {

    /**
     * Creates new form frmComboBox2
     */
    public frmComboBox2() {
        initComponents();
    }
    //Hàm hiển thị các đối tượng từ mảng lên JComboBox
    public void HienthiMonhoc()
    {
        //tạo mảng chứa các môn học để đẩy vào combobox
        Vector<clsMonhoc> dsMonhoc = new Vector<clsMonhoc>();
        //tạo các đối tượng - Object - clsMonhoc
        clsMonhoc monhoc1 = new clsMonhoc("MH01", "Lập trình Java",40);
        clsMonhoc monhoc2 = new clsMonhoc("MH02", "Lập trình Web JSP",60);
        clsMonhoc monhoc3 = new clsMonhoc("MH03", "Cơ sở dữ liệu MySQL",20);
        clsMonhoc monhoc4 = new clsMonhoc("MH04", "Lập trình PHP",30);
        //thêm các môn học vào mảng
        dsMonhoc.add(monhoc1);
        dsMonhoc.add(monhoc2);
        dsMonhoc.add(monhoc3);
        dsMonhoc.add(monhoc4);
        //tạo đối tượng DefaultComboBoxModel để chứa dữ liệu của JComboBox 
        DefaultComboBoxModel model = new DefaultComboBoxModel(dsMonhoc);
        //đưa nội dung từ model vào JComboBox
        cbbMonhoc.setModel(model);
        cbbMonhoc.insertItemAt("Mời chọn môn học",0);
        cbbMonhoc.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnHienthi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbbMonhoc = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GẮN CÁC ĐỐI TƯỢNG VÀO TỪNG DÒNG COMBOBOX");

        btnHienthi.setText("HIỂN THỊ");
        btnHienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienthiActionPerformed(evt);
            }
        });

        jLabel2.setText("Môn học:");

        cbbMonhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMonhocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnHienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbbMonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbbMonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(btnHienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienthiActionPerformed
        // TODO add your handling code here:
        clsMonhoc monhoc = new clsMonhoc("MH01", "Lập trình Java");
        JOptionPane.showMessageDialog(this, monhoc);
    }//GEN-LAST:event_btnHienthiActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //các lệnh thực hiện khi cửa số bắt đầu hiển thị
        HienthiMonhoc();
    }//GEN-LAST:event_formWindowOpened

    private void cbbMonhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMonhocActionPerformed
        // TODO add your handling code here:
        int i = cbbMonhoc.getSelectedIndex();//lấy vị trí dòng chọn
        if(i>0)
        {
            //lấy dữ liệu từ dòng i dang Object ép kiểu về clsMonhoc
            clsMonhoc monhoc = (clsMonhoc)cbbMonhoc.getSelectedItem();
            JOptionPane.showMessageDialog(this, 
                    "Mã môn:" + monhoc.getMamon() + ",Tên:" + monhoc.getTenmon()
                    + ", Số giờ:" + monhoc.getSogio());
        }
    }//GEN-LAST:event_cbbMonhocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmComboBox2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmComboBox2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmComboBox2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmComboBox2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmComboBox2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienthi;
    private javax.swing.JComboBox<String> cbbMonhoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
