/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DemoJDBC;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Manh Truong
 */
public class frmDanhsachSinhvien extends javax.swing.JFrame {

    /**
     * Creates new form frmDanhsachSinhvien
     */
    public frmDanhsachSinhvien() {
        initComponents();
    }
    public void HienthiDSSV()
    {
        //kết nối đến CSDL
        Connection cnn = CSDL.Database.KetnoiCSDL();
        if(cnn==null)
        {
            JOptionPane.showMessageDialog(this, "Lỗi Kết nối CSDL");
            return;
        }
        else
        {
            //JOptionPane.showMessageDialog(this, "Kết nối CSDL Thành công");
            //truy vấn dữ liệu từ bảng tbSinhvien và hiển thị lên JTable
            String sql = "SELECT * FROM tbSinhvien";
            try {
                //đối tượng PreparedStatement để thực thi câu lệnh SQL từ CSDL cnn
                PreparedStatement stm = cnn.prepareStatement(sql);
                ResultSet rs = stm.executeQuery(sql);//thực thi lệnh Select trả về Resulset
                //lặp các dòng từ rs và hiển thị và JTable
                DefaultTableModel dtm = (DefaultTableModel) tblDSSinhvien.getModel();
                dtm.setRowCount(0);//xóa các dòng dữ liệu cũ trong JTable nếu có
                int dem =0;
                while(rs.next())//lặp từng dòng của kết quả truy vấn
                {
                    String masv = rs.getString("masv");
                    String hoten = rs.getString("hoten");
                    String dienthoai = rs.getString("dienthoai");
                    dtm.addRow(new Object[] {masv, hoten, dienthoai});
                    dem++;
                }
                if(dem==0)
                    JOptionPane.showMessageDialog(this, "Chưa có sinh viên");
            } catch (SQLException ex) {
                Logger.getLogger(frmDanhsachSinhvien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSSinhvien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMasv = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtDienthoai = new javax.swing.JTextField();
        btnThemSinhvien = new javax.swing.JButton();
        btnSuaSinhvien = new javax.swing.JButton();
        btnXoasinhvien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sinh viên");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH SINH VIÊN");

        tblDSSinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sinh viên", "Họ và tên", "Điện thoại"
            }
        ));
        tblDSSinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSSinhvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSSinhvien);

        jLabel2.setText("Mã SV:");

        jLabel3.setText("Họ tên:");

        jLabel4.setText("Điện thoại:");

        btnThemSinhvien.setText("THÊM SINH VIÊN");
        btnThemSinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSinhvienActionPerformed(evt);
            }
        });

        btnSuaSinhvien.setText("SỬA SINH VIÊN");
        btnSuaSinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSinhvienActionPerformed(evt);
            }
        });

        btnXoasinhvien.setText("XÓA SINH VIÊN");
        btnXoasinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoasinhvienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMasv)
                                            .addComponent(txtHoten)
                                            .addComponent(txtDienthoai, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThemSinhvien)
                                .addGap(18, 18, 18)
                                .addComponent(btnSuaSinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoasinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtMasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtDienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemSinhvien)
                    .addComponent(btnSuaSinhvien)
                    .addComponent(btnXoasinhvien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        HienthiDSSV();
    }//GEN-LAST:event_formWindowOpened

    private void btnThemSinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSinhvienActionPerformed
        // TODO add your handling code here:
        String masv = this.txtMasv.getText();
        String hoten = this.txtHoten.getText();
        String dienthoai = this.txtDienthoai.getText();
        Connection cnn = CSDL.Database.KetnoiCSDL();
        if(cnn==null)
        {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối CSDL");
            return;
        }
        String sql = "INSERT INTO tbSinhvien VALUES(?, ?, ?)";
        try {
            PreparedStatement stm = cnn.prepareStatement(sql);
            //gán giá trị vào các tham số ? của lệnh SQL
            stm.setString(1, masv);
            stm.setString(2, hoten);
            stm.setString(3, dienthoai);
            int n = stm.executeUpdate();//trả về số dòng insert
            if(n>0)
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                HienthiDSSV();//gọi hàm hiển thị danh sách sv mới lên JTable
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "LỖI SQL");
            Logger.getLogger(frmDanhsachSinhvien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemSinhvienActionPerformed

    private void btnXoasinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoasinhvienActionPerformed
        // TODO add your handling code here:
        //lấy vị trí dòng chọn và lấy mã sinh viên cần xóa 
        int i = this.tblDSSinhvien.getSelectedRow();
        if(i<0)
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sinh viên cần xóa");
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) tblDSSinhvien.getModel();
        //lấy dữ liệu từ dòng i, cột 0 (mã sinh viên)
        String masv = (String)dtm.getValueAt(i, 0);
        int res = JOptionPane.showConfirmDialog(this, "Xóa sinh viên", "Chắc chán xóa?", 
                                                JOptionPane.YES_NO_OPTION);
        if(res==JOptionPane.YES_OPTION)//nếu nhấn Yes
        {
            Connection cnn = CSDL.Database.KetnoiCSDL();
            if(cnn==null)
            {
                JOptionPane.showMessageDialog(this, "Lỗi kết nối CSDL");
                return;
            }
            String sql = "DELETE FROM tbSinhvien WHERE masv = ?";
           try {
                PreparedStatement stm = cnn.prepareStatement(sql);
                stm.setString(1, masv);
                int n = stm.executeUpdate();//thực hiện lệnh sql và trả về số dòng được thực hiện
                if(n>0)
                {
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    HienthiDSSV();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "LỖI SQL!");
                Logger.getLogger(frmDanhsachSinhvien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnXoasinhvienActionPerformed

    private void tblDSSinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSSinhvienMouseClicked
        // TODO add your handling code here:
        int i = this.tblDSSinhvien.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) this.tblDSSinhvien.getModel();
        String masv =  (String)dtm.getValueAt(i, 0);
        String hoten = (String)dtm.getValueAt(i, 1);
        String dienthoai = (String)dtm.getValueAt(i, 2);
        this.txtMasv.setText(masv);
        this.txtHoten.setText(hoten);
        this.txtDienthoai.setText(dienthoai);
    }//GEN-LAST:event_tblDSSinhvienMouseClicked

    private void btnSuaSinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSinhvienActionPerformed
        // TODO add your handling code here:
        //lấy vị trí dòng chọn và lấy mã sinh viên cần xóa 
        int i = this.tblDSSinhvien.getSelectedRow();
        if(i<0)
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sinh viên cần sửa");
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) tblDSSinhvien.getModel();
        //lấy dữ liệu từ dòng i, cột 0 (mã sinh viên)
        String masv = (String)dtm.getValueAt(i, 0);
        int res = JOptionPane.showConfirmDialog(this, "Sửa sinh viên", "Chắc chắn sửa?", 
                                                JOptionPane.YES_NO_OPTION);
        if(res==JOptionPane.YES_OPTION)//nếu nhấn Yes
        {
            Connection cnn = CSDL.Database.KetnoiCSDL();
            if(cnn==null)
            {
                JOptionPane.showMessageDialog(this, "Lỗi kết nối CSDL");
                return;
            }
            String masvmoi = this.txtMasv.getText();
            String hotenmoi = this.txtHoten.getText();
            String dienthoaimoi = this.txtDienthoai.getText();
            String sql = "UPDATE tbSinhvien SET masv = ?, hoten = ?, dienthoai = ? WHERE masv = ?";
           try {
                PreparedStatement stm = cnn.prepareStatement(sql);
                stm.setString(1, masvmoi);
                stm.setString(2, hotenmoi);
                stm.setString(3, dienthoaimoi);
                stm.setString(4, masv);
                int n = stm.executeUpdate();//thực hiện lệnh sql và trả về số dòng được thực hiện
                if(n>0)
                {
                    JOptionPane.showMessageDialog(this, "Sửa thành công!");
                    HienthiDSSV();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "LỖI SQL!");
                Logger.getLogger(frmDanhsachSinhvien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSuaSinhvienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDanhsachSinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDanhsachSinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDanhsachSinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDanhsachSinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDanhsachSinhvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaSinhvien;
    private javax.swing.JButton btnThemSinhvien;
    private javax.swing.JButton btnXoasinhvien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDSSinhvien;
    private javax.swing.JTextField txtDienthoai;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMasv;
    // End of variables declaration//GEN-END:variables
}
