package DEMO_MENU_MotSobaiTap;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//package java_ngay24_giaodien;

/**
 *
 * @author TEACHER
 */
public class MenuChinh extends javax.swing.JFrame {

    /**
     * Creates new form module1_bai1_4_menu
     */
    public MenuChinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuBai1 = new javax.swing.JMenu();
        mniBai1_1 = new javax.swing.JMenuItem();
        mniBai1_2 = new javax.swing.JMenuItem();
        mniBai1_5 = new javax.swing.JMenuItem();
        mniKhaosat = new javax.swing.JMenuItem();
        mnuBai2 = new javax.swing.JMenu();
        mnuBai3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuBai1.setText("Bài tập");

        mniBai1_1.setText("Bài 1.1 - Thông tin liên hệ");
        mniBai1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBai1_1ActionPerformed(evt);
            }
        });
        mnuBai1.add(mniBai1_1);

        mniBai1_2.setText("Bài 1.2 - Thêm mới thông tin");
        mniBai1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBai1_2ActionPerformed(evt);
            }
        });
        mnuBai1.add(mniBai1_2);

        mniBai1_5.setText("Bài 1.5 - Chọn toán tử");
        mniBai1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBai1_5ActionPerformed(evt);
            }
        });
        mnuBai1.add(mniBai1_5);

        mniKhaosat.setText("Bài 1.6 - Khảo sát thông tin");
        mniKhaosat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhaosatActionPerformed(evt);
            }
        });
        mnuBai1.add(mniKhaosat);

        jMenuBar1.add(mnuBai1);

        mnuBai2.setText("Menu 2");
        jMenuBar1.add(mnuBai2);

        mnuBai3.setText("Menu 3");
        jMenuBar1.add(mnuBai3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniBai1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBai1_1ActionPerformed
        // TODO add your handling code here:
        module1_bai1_1 bai1_1 = new module1_bai1_1();
        bai1_1.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mniBai1_1ActionPerformed

    private void mniBai1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBai1_2ActionPerformed
        // TODO add your handling code here:
        module1_bai1_2 bai1_2 = new module1_bai1_2();
        bai1_2.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mniBai1_2ActionPerformed

    private void mniBai1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBai1_5ActionPerformed
        // TODO add your handling code here:
        module1_bai1_5_toantu bai1_5 = new module1_bai1_5_toantu();
        bai1_5.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mniBai1_5ActionPerformed

    private void mniKhaosatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhaosatActionPerformed
        // TODO add your handling code here:
        module1_bai1_6 bai1_6 = new module1_bai1_6();
        bai1_6.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mniKhaosatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniBai1_1;
    private javax.swing.JMenuItem mniBai1_2;
    private javax.swing.JMenuItem mniBai1_5;
    private javax.swing.JMenuItem mniKhaosat;
    private javax.swing.JMenu mnuBai1;
    private javax.swing.JMenu mnuBai2;
    private javax.swing.JMenu mnuBai3;
    // End of variables declaration//GEN-END:variables
}
