/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package DEMO_MENU_MotSobaiTap;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author TEACHER
 */
public class module1_bai1_5_toantu extends javax.swing.JFrame {

    /**
     * Creates new form module1_bai1_5_toantu
     */
    public module1_bai1_5_toantu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbbNhomToanTu = new javax.swing.JComboBox();
        cbbToanTu = new javax.swing.JComboBox();
        txtSohang1 = new javax.swing.JTextField();
        txtSohang2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtKetqua = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nhóm toán tử");

        jLabel2.setText("Toán tử");

        jLabel3.setText("Số hạng thứ nhất");

        jLabel4.setText("Số hạng thứ hai");

        jLabel5.setText("Kết quả");

        cbbNhomToanTu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Mời chọn nhóm toán tử ---", "Toán học", "Quan hệ", "Logic" }));
        cbbNhomToanTu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbNhomToanTuItemStateChanged(evt);
            }
        });
        cbbNhomToanTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNhomToanTuActionPerformed(evt);
            }
        });

        cbbToanTu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Toán tử ---" }));

        jButton1.setText("Tính toán");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addComponent(cbbNhomToanTu, 0, 1, Short.MAX_VALUE)
                    .addComponent(cbbToanTu, 0, 148, Short.MAX_VALUE)
                    .addComponent(txtSohang1)
                    .addComponent(txtSohang2)
                    .addComponent(txtKetqua))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbbNhomToanTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbToanTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSohang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSohang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKetqua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbbNhomToanTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNhomToanTuActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(rootPane, evt.getActionCommand());
        if(cbbNhomToanTu.getSelectedIndex()==1)
        {
            String[] cacphantu = new String[6];
            cacphantu[0] = "--- Chọn phép toán ---";
            cacphantu[1] = "Phép cộng \" + \"";
            cacphantu[2] = "Phép trừ \" - \"";
            cacphantu[3] = "Phép nhân \" * \"";
            cacphantu[4] = "Phép chia \" / \"";
            ComboBoxModel cbbmodel = new DefaultComboBoxModel(cacphantu);
            cbbToanTu.setModel(cbbmodel);
        }
        else if(cbbNhomToanTu.getSelectedIndex()==2)
        {
            String[] cacphantu = new String[6];
            cacphantu[0] = "--- Chọn phép toán ---";
            cacphantu[1] = "Nhỏ hơn \" < \"";
            cacphantu[2] = "Lớn hơn \" > \"";
            cacphantu[3] = "Bằng \" == \"";
            cacphantu[4] = "Không bằng \" != \"";
            ComboBoxModel cbbmodel = new DefaultComboBoxModel(cacphantu);
            cbbToanTu.setModel(cbbmodel); 
        }
    }//GEN-LAST:event_cbbNhomToanTuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Double n1 = Double.parseDouble(txtSohang1.getText());
        Double n2 = Double.parseDouble(txtSohang2.getText());
        Double ketqua =0.0;
        if( cbbNhomToanTu.getSelectedIndex()==1 && cbbToanTu.getSelectedIndex()==1)
        {
            ketqua = n1+n2;
        }
        else if( cbbNhomToanTu.getSelectedIndex()==1 && cbbToanTu.getSelectedIndex()==2)
        {
            ketqua = n1-n2;
        }
        else if( cbbNhomToanTu.getSelectedIndex()==1 && cbbToanTu.getSelectedIndex()==3)
        {
            ketqua = n1*n2;
        }
        else if( cbbNhomToanTu.getSelectedIndex()==1 && cbbToanTu.getSelectedIndex()==4)
        {
            ketqua = n1/n2;
        }
        //......
        txtKetqua.setText(ketqua.toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbbNhomToanTuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbNhomToanTuItemStateChanged
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"id :" + evt.getItem().toString());
        if(evt.getStateChange()== java.awt.event.ItemEvent.SELECTED)
            JOptionPane.showMessageDialog(rootPane,"Chon phan tu moi :" + evt.getItem().toString());
        else
            JOptionPane.showMessageDialog(rootPane,"Bo chon phan tu cu: "+ evt.getItem().toString());
    }//GEN-LAST:event_cbbNhomToanTuItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(module1_bai1_5_toantu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(module1_bai1_5_toantu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(module1_bai1_5_toantu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(module1_bai1_5_toantu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new module1_bai1_5_toantu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbbNhomToanTu;
    private javax.swing.JComboBox cbbToanTu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtKetqua;
    private javax.swing.JTextField txtSohang1;
    private javax.swing.JTextField txtSohang2;
    // End of variables declaration//GEN-END:variables
}
