/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package DEMO_MENU_MotSobaiTap;

import javax.swing.table.DefaultTableModel;



/**
 *
 * @author TEACHER
 */
public class module1_bai1_6 extends javax.swing.JFrame {

    /**
     * Creates new form module1_bai1_6
     */
    DefaultTableModel tablemodel;
    public module1_bai1_6() {
        initComponents();
        txaKhac.setEnabled(false);
        tablemodel = new DefaultTableModel();
        tablemodel.addColumn("Họ tên");
        tablemodel.addColumn("Giới tính");
        tablemodel.addColumn("Sở thích");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGioitinh = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        ckbDulich = new javax.swing.JCheckBox();
        ckbDocsach = new javax.swing.JCheckBox();
        ckbLeonui = new javax.swing.JCheckBox();
        ckbKhac = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaKhac = new javax.swing.JTextArea();
        btbGhiThongTin = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThongtin = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Họ tên");

        jLabel2.setText("Giới tính");

        jLabel3.setText("Sở thích");

        btgGioitinh.add(rdNam);
        rdNam.setText("Nam");

        btgGioitinh.add(rdNu);
        rdNu.setText("Nữ");

        ckbDulich.setText("Du lịch");

        ckbDocsach.setText("Đọc sách");

        ckbLeonui.setText("Leo núi");

        ckbKhac.setText("Khác");
        ckbKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbKhacActionPerformed(evt);
            }
        });

        txaKhac.setColumns(20);
        txaKhac.setLineWrap(true);
        txaKhac.setRows(5);
        jScrollPane1.setViewportView(txaKhac);

        btbGhiThongTin.setText("Ghi thông tin");
        btbGhiThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbGhiThongTinActionPerformed(evt);
            }
        });

        tblThongtin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Họ tên", "Giới tính", "Sở thích"
            }
        ));
        jScrollPane3.setViewportView(tblThongtin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdNam)
                                .addGap(18, 18, 18)
                                .addComponent(rdNu)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ckbDulich)
                        .addGap(18, 18, 18)
                        .addComponent(ckbLeonui)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(ckbDocsach)
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btbGhiThongTin)
                            .addComponent(ckbKhac)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdNam)
                            .addComponent(rdNu))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ckbDulich)
                    .addComponent(ckbDocsach)
                    .addComponent(ckbLeonui))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbKhac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btbGhiThongTin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ckbKhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbKhacActionPerformed
        // TODO add your handling code here:
        if( ckbKhac.isSelected())
            txaKhac.setEnabled(true);
        else
        {
            txaKhac.setEnabled(false);
            txaKhac.setText("");
        }
    }//GEN-LAST:event_ckbKhacActionPerformed

    private void btbGhiThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbGhiThongTinActionPerformed
        // TODO add your handling code here:
       
        //lấy thông tin họ tên, giới tính, sở thích từ form
        String hoten = txtHoten.getText();
        String gioitinh = "Nữ";
        if(btgGioitinh.getSelection().equals(rdNam.getModel()))
        {
            gioitinh = "Nam";
        }
        String sothich = "";
        if( ckbDulich.isSelected())
        {
            if( !sothich.equals(""))
                sothich += ", ";
         
            sothich += ckbDulich.getText();
        }
        if( ckbDocsach.isSelected())
        {
            if( !sothich.equals(""))
                sothich += ", ";
         
            sothich += ckbDocsach.getText();
        }
        if( ckbLeonui.isSelected())
        {        
            if( !sothich.equals(""))
                sothich += ", ";
            sothich += ckbLeonui.getText();
        }
        if( ckbKhac.isSelected())
        {
             if( !sothich.equals(""))
                sothich += ", ";
            sothich += txaKhac.getText();
        }        
//chèn dòng mới vào table
        tablemodel.addRow(new Object[] {hoten,gioitinh,sothich} );
        tblThongtin.setModel(tablemodel);
    }//GEN-LAST:event_btbGhiThongTinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(module1_bai1_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(module1_bai1_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(module1_bai1_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(module1_bai1_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new module1_bai1_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbGhiThongTin;
    private javax.swing.ButtonGroup btgGioitinh;
    private javax.swing.JCheckBox ckbDocsach;
    private javax.swing.JCheckBox ckbDulich;
    private javax.swing.JCheckBox ckbKhac;
    private javax.swing.JCheckBox ckbLeonui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tblThongtin;
    private javax.swing.JTextArea txaKhac;
    private javax.swing.JTextField txtHoten;
    // End of variables declaration//GEN-END:variables
}
