/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyNotePad;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class MyNotePadForm extends javax.swing.JFrame {

    /**
     * Creates new form MyNotePadForm
     */
    public MyNotePadForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        edt_noidung = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnu_HeThong = new javax.swing.JMenu();
        mni_new = new javax.swing.JMenuItem();
        mni_save = new javax.swing.JMenuItem();
        mni_open = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(edt_noidung);

        mnu_HeThong.setText("Hệ thống");

        mni_new.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mni_new.setText("Tạo mới");
        mni_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_newActionPerformed(evt);
            }
        });
        mnu_HeThong.add(mni_new);

        mni_save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mni_save.setText("Ghi ra tệp mới");
        mni_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_saveActionPerformed(evt);
            }
        });
        mnu_HeThong.add(mni_save);

        mni_open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mni_open.setText("Mở tệp");
        mni_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_openActionPerformed(evt);
            }
        });
        mnu_HeThong.add(mni_open);

        jMenuBar1.add(mnu_HeThong);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mni_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_saveActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showSaveDialog(this);
        File file = fc.getSelectedFile();
        String noidung = edt_noidung.getText();

        try {
            FileOutputStream fo = new FileOutputStream(file,false);
            PrintWriter pw =  new PrintWriter(fo);
            pw.println(noidung);
            pw.close();
            try {
                fo.close();
            } catch (IOException ex) {
                Logger.getLogger(MyNotePadForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MyNotePadForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mni_saveActionPerformed

    private void mni_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_openActionPerformed
        FileReader fr = null;
        BufferedReader br = null;
        JFileChooser fc = new JFileChooser();
        try {
            fc.showOpenDialog(this);
            File file = fc.getSelectedFile();
            
            // TODO add your handling code here:
            
            fr = new FileReader(file); //mở tệp để đọc
            br = new BufferedReader(fr);//truyền tệp đã mở từ đối tượng fr để đọc
            //làm việc với tệp
            String str;//đọc từng dòng của tệp
            String noidung ="";
            while( (str = br.readLine())!=null ){
                if(noidung.equals(""))
                    noidung += str;
                else
                    noidung += "\n" + str;
            }
            edt_noidung.setText(noidung);
        }catch (FileNotFoundException ex) {
            Logger.getLogger(MyNotePadForm.class.getName()).log(Level.SEVERE, null, ex);
        }catch (IOException ex) {
                Logger.getLogger(MyNotePadForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            try {
                if(br!=null)br.close();
                if(fr!=null)fr.close();
            } catch (IOException ex) {
                Logger.getLogger(MyNotePadForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_mni_openActionPerformed

    private void mni_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_newActionPerformed
        // TODO add your handling code here:
        edt_noidung.setText("");
    }//GEN-LAST:event_mni_newActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyNotePadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyNotePadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyNotePadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyNotePadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyNotePadForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane edt_noidung;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mni_new;
    private javax.swing.JMenuItem mni_open;
    private javax.swing.JMenuItem mni_save;
    private javax.swing.JMenu mnu_HeThong;
    // End of variables declaration//GEN-END:variables
}
