/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Baiitap_Tabs_Tinhtien;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FrmCollectMoney extends javax.swing.JFrame {

    /**
     * Creates new form FrmCollectMoney
     */
    public FrmCollectMoney() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabCollectMoney = new javax.swing.JTabbedPane();
        panelTienDien = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtChisodau = new javax.swing.JTextField();
        txtChisocuoi = new javax.swing.JTextField();
        txtTienDien = new javax.swing.JTextField();
        btnTinhTienDien = new javax.swing.JButton();
        panelInternet = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Chỉ số đầu:");

        jLabel2.setText("Chỉ số cuối:");

        jLabel3.setText("Thành tiền:");

        btnTinhTienDien.setText("Tình tiền điện");
        btnTinhTienDien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienDienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTienDienLayout = new javax.swing.GroupLayout(panelTienDien);
        panelTienDien.setLayout(panelTienDienLayout);
        panelTienDienLayout.setHorizontalGroup(
            panelTienDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTienDienLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelTienDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panelTienDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTienDien, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(txtChisocuoi, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(txtChisodau)
                    .addComponent(btnTinhTienDien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        panelTienDienLayout.setVerticalGroup(
            panelTienDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTienDienLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelTienDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtChisodau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelTienDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtChisocuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTinhTienDien)
                .addGap(32, 32, 32)
                .addGroup(panelTienDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTienDien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tabCollectMoney.addTab("Tính tiền điện", panelTienDien);

        javax.swing.GroupLayout panelInternetLayout = new javax.swing.GroupLayout(panelInternet);
        panelInternet.setLayout(panelInternetLayout);
        panelInternetLayout.setHorizontalGroup(
            panelInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        panelInternetLayout.setVerticalGroup(
            panelInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        tabCollectMoney.addTab("Tính tiền Internet", panelInternet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabCollectMoney)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabCollectMoney)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhTienDienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienDienActionPerformed
        // TODO add your handling code here:
        String strSodau = txtChisodau.getText();
        String strSocuoi = txtChisocuoi.getText();
        if(strSodau.equals("") ||strSocuoi.equals(""))
        {
            JOptionPane.showMessageDialog(panelInternet, "Lỗi nhập chỉ số điện");
            return;
        }
        double sodau = Double.parseDouble(strSodau);
        double socuoi = Double.parseDouble(strSocuoi);
        CollectMoney money = new CollectMoneyElectric(sodau, socuoi);
        double sotien = money.calculateMoney();
        txtTienDien.setText(String.valueOf(sotien));
    }//GEN-LAST:event_btnTinhTienDienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCollectMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCollectMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCollectMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCollectMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCollectMoney().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTinhTienDien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelInternet;
    private javax.swing.JPanel panelTienDien;
    private javax.swing.JTabbedPane tabCollectMoney;
    private javax.swing.JTextField txtChisocuoi;
    private javax.swing.JTextField txtChisodau;
    private javax.swing.JTextField txtTienDien;
    // End of variables declaration//GEN-END:variables
}
